apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment-dev
  labels:
    app: nodejs-deployment-dev

spec:
  selector:
    matchLabels:
      app: nodejs-deployment-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-deployment-dev
    spec:
      containers:
        - name: nodejs-container
          image: DockerImageToPull
          ports:
            - containerPort: 3000

---
apiVersion: v1 
kind: Service
metadata: 
  name: nodejs-service-dev
spec:
  type: NodePort
  selector:
    app: nodejs-deployment-dev
  ports:
    - port: 3000 # The port that the service is running on in the cluster
      targetPort: 3000 # The port exposed by the service
      protocol: TCP
      nodePort: 31000  
  
