apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment-prod
  labels:
    app: nodejs-deployment-prod

spec:
  selector:
    matchLabels:
      app: nodejs-deployment-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-deployment-prod
    spec:
      containers:
        - name: nodejs-container-prod
          image: DockerImageToPull
          ports:
            - containerPort: 3000

---
apiVersion: v1 
kind: Service
metadata: 
  name: nodejs-service-prod
spec:
  type: NodePort
  selector:
    app: nodejs-deployment-prod
  ports:
    - port: 3000 # The port that the service is running on in the cluster
      targetPort: 3000 # The port exposed by the service
      protocol: TCP
      nodePort: 32000  
  
